### ISSUE TITLE
Auto-brightness setting not remembered

### ISSUE THREAD

**Issue by 153957** [Kalvin126/BrightnessMenulet#10]
My monitor does not support Auto-brightness so I disabled it.
However, whenever I restart the app the feature is enabled again.
Is this intentional, or should the setting be remembered by the app?

**Comment by wise-rice** [comment]
With me it is exactly the other way around.
Do you want to swap?

**Comment by Kalvin126** [comment]
It should not be intentional. There should be a setting in preferences to auto start auto brightness on startup. Can you make sure it is off and try restarting the menulet?

**Comment by 153957** [comment]
I did, it was reenabled upon startup. What name should the preferences files have? Are the preferences stored in `~/Library/Preferences/`? Perhaps I can check if it exists and contains the correct keys.

**Comment by Kalvin126** [comment]
yes, you should find `com.redpanda.BrightnessMenulet.plist` in that folder

**Comment by Kalvin126** [comment]
Try to toggle Start Auto-Brightness on startup on and off to check that it actually changes the value as well

**Comment by 153957** [comment]
Ah! That's it! This has to be changed in the Preferences, I thought it would remember the last settings in the menu. I did see the '... on startup' settings but did not read carefully. I simply assumed it was to make the app start when logging in.

So, the preferences file exists and the setting is properly saved and remembered when restarting the app.

Thanks for the help, sorry for the misunderstanding.
