### ISSUE TITLE
Dell P2412H not working. How do you undo the brightness change manually?

### ISSUE THREAD

**Issue by rally25rs** [Kalvin126/BrightnessMenulet#11]
The app comes up, but:
- all the slider bars don't work (aren't draggable).
- If you manually type numbers in the box, it sometimes changes the brightness.
- Clicking the "debug" button causes the pinwheel of death for a while (minutes), then the app starts responding again.
- Once the app dims the display, you can never get brightness back. I've exited the app and rebooted and unplugged/replugged the display but it stays dim.

Is there a way to restore/undo the brightness change if the app is broken and can't do it?

**Comment by mblatchford** [comment]
I'm using a Dell U2415 and if I disconnect the monitor (running as a secondary display off my laptop), and reconnect it later, BrightnessMenulet recognizes the display, but freezes the sliderbars like you've experienced. I've found simply quitting and reopening BrightnessMenulet brings back full functionality if you haven't tried that yet.

**Comment by 153957** [comment]
Can you not use the physical control buttons on the monitor to set the brightness back to the old value?

What 'debug' button? I don't see any..

**Comment by rally25rs** [comment]
@153957 Thanks for the reminder about the physical buttons. Makes me feel dumb :) I actually didn't think direct control over the on-display brightness was possible, and assumed the app was just fiddling with the OS's display color profile or something like that.

The "debug" button I mentioned is in the "Preferences" screen at the top. I see a display selection dropdown, then Debug and Refresh buttons.

**Comment by Kalvin126** [comment]
The app does not take over control from your monitor, it merely sends messages to do something directly to your monitor. That being said, that is odd behavior. The debug button is likely to do that. If you open the console application and filter for BrightnessMenulet, you should see the debug log being generated. Would you mind sending that to me?  I think I know where to get a P2412h to test on. 
- Kalvin

**Comment by 153957** [comment]
@rally25rs Ah, I was running an older version of the app which did not have the Debug button.

**Comment by Kalvin126** [comment]
Closing issue as the issue seems to be with the monitor. I can read values but writing only changes brightness to one value.

**Comment by rally25rs** [comment]
@Kalvin126 would it be appropriate to add to add this monitor to the "not working" list in the Readme then?

**Comment by Kalvin126** [comment]
yes, you can make a pull request or I could add it in the next commit.
