### ISSUE TITLE
Flux

### ISSUE THREAD

**Issue by yannickwurm** [Kalvin126/BrightnessMenulet#13]
This is awesome - thanks v much! (Dell U2715h)

Any chance for flux integration (perhaps increasing brightness based on current white point?)

cheers
y

**Comment by Kalvin126** [comment]
You are welcome! I do not think there are public apis for f.lux, I could not find anything on their site, so I do not think there is a chance for it at the moment. Maybe when Apple implements Night Shift for OS X haha.
