### ISSUE TITLE
Is it possible to control the volume of DP Source

### ISSUE THREAD

**Issue by sequencer** [Kalvin126/BrightnessMenulet#18]
Your know, MAC doesn't support the volume control,
Maybe there is a DCC setting to set the volume?
Just guess.

**Comment by Kalvin126** [comment]
Oh yes, If you have a monitor that implements VCP address 0x62 properly, then it would be possible to control a DP monitor's volume level. Try to use kfix's ddcctl [https://github.com/kfix/ddcctl](url) to toggle your monitor's volume. Be sure to read his read me.
