### ISSUE TITLE
Link brightness of external monitor to internal monitor

### ISSUE THREAD

**Issue by jordibruin** [Kalvin126/BrightnessMenulet#8]
Thanks so much for this, solved all my brightness problems with my external monitor.

Ideally I would want to have the same brightness across both my internal and external monitor.

Not sure if it's possible to link the two though?

**Comment by jadegraaf** [comment]
This would be awesome!

**Comment by Kalvin126** [comment]
Hm I do suppose locking brightness across all monitors would be useful especially for those with identical monitors. I'll included it in the next commit.

**Comment by Kalvin126** [comment]
Oh, wait I misinterpreted your request. It would be hard as a brightness value one display to another would be different. Calculating brightness output on the displays would require external tools.

It would be possible on identical external monitors as they would be assumed to have similar brightness levels.

**Comment by Kalvin126** [comment]
Oh, wait I misinterpreted your request. It would be hard as a brightness value one display to another would be different. Calculating brightness output on the displays would require external tools.

It would be possible on identical external monitors as they would be assumed to have similar brightness levels.

**Comment by Kalvin126** [comment]
Closing issue as external tools would be needed to measure brightness output levels to match.

**Comment by florianbeck** [comment]
Hi, please have a look at my [fork of your project](https://github.com/florianbeck/BrightnessMenulet). I added a function to follow the main display's brightness (instead of the light sensor) and some other features.
